spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
